<<: &shared
  language_name: Southern East Cree
mappings:
  - display_name: Northern East Cree Normalization
    in_lang: crj
    out_lang: crj-norm
    type: mapping
    authors:
      - Delasie Torkornoo
      - Aidan Pine
    mapping: crj_norm.json
    rule_ordering: as-written
    <<: *shared
  - display_name: Southern East Cree to IPA
    in_lang: crj-norm
    out_lang: crj-ipa
    type: mapping
    authors:
      - David Huggins Daines
      - Patrick Littell
    mapping: crj_to_ipa.json
    rule_ordering: as-written
    <<: *shared
  - display_name: Southern East Cree IPA to English IPA
    in_lang: crj-ipa
    out_lang: eng-ipa
    type: mapping
    mapping: crj_ipa_to_eng_ipa.json
    rule_ordering: as-written
    <<: *shared
