sudo: required
dist: xenial

language: python
python:
  - "3.6"

# install system dependencies here with apt-get.
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y python3 python3-pip python-dev build-essential

# install python dependencies including this package in the travis
# virtualenv
install:
  # Install Python dependencies
  - pip3 install -r /home/travis/build/roedoejet/g2p/requirements.txt
  # Install g2p
  - cd /home/travis/build/roedoejet/g2p && pip3 install -e .
  # Legal check: make sure we don't introduce GPL dependencies
  - pip3 install pip-licenses
  - if pip-licenses | grep -v 'Artistic License' | grep -v LGPL | grep GNU; then echo 'Please avoid introducing *GPL dependencies'; false; fi
  # Install testing requirements
  - pip3 install coverage
  - pip3 install coveralls
  - pip3 install gunicorn

before_script:
  - gunicorn --worker-class eventlet -w 1 g2p.app:APP --no-sendfile --bind 0.0.0.0:5000 --daemon

# commands to run the testing suite. if any of these fail, travis lets us know
script: 
  - cd /home/travis/build/roedoejet/g2p && coverage run --source g2p run_tests.py dev

# commands to run after the tests successfully complete
after_success:
  - coveralls
  - if git status | grep -E 'static.*json|mapping.*pkl'; then echo 'g2p databases out of date, please run "g2p update" and commit the results.'; false; else echo OK; fi
