language_name: generated
mappings:
  - display_name: Atikamekw IPA to English IPA
    in_lang: atj-ipa
    language_name: Atikamekw
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    rules_path: atj-ipa_to_eng-ipa.json
  - author: Generated 2019-09-26 13:48:19.852180
    authors:
      - Generated 2020-07-06 16:39:58.770641
    display_name: Danish IPA to English IPA
    in_lang: dan-ipa
    language_name: Danish
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    rules_path: dan-ipa_to_eng-ipa.json
  - author: Generated 2020-02-06 11:01:41.458466
    authors:
      - Generated 2021-04-14 16:34:39.868437
      - Tidied up 2021-04-14 by Eric Joanis
    display_name: French IPA to English IPA
    in_lang: fra-ipa
    language_name: French
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    rules_path: fra-ipa_to_eng-ipa.json
  - author: Generated 2019-10-24 16:21:41.605592
    authors:
      - Generated 2022-04-12 11:26:30.098188
    display_name: SENĆOŦEN IPA to English IPA
    in_lang: str-ipa
    language_name: SENĆOŦEN
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    rules_path: str-ipa_to_eng-ipa.json
  - author: Generated 2019-10-24 16:21:41.605592
    authors:
      - Generated 2022-04-12 11:26:30.098188
    display_name: SENĆOŦEN IPA to English IPA
    in_lang: str-ipa
    language_name: SENĆOŦEN
    out_lang: hamming-eng-ipa
    rule_ordering: apply-longest-first
    rules_path: str-ipa_to_hamming-eng-ipa.json
  - author: Generated 2019-10-23 11:18:26.278696
    display_name: Algonquin IPA to English IPA
    in_lang: alq-ipa
    language_name: Algonquin
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    rules_path: alq-ipa_to_eng-ipa.json
  - authors:
      - Generated 2020-03-06 00:15:29.676518
    display_name: see-ipa IPA to eng-ipa IPA
    in_lang: see-ipa
    language_name: see-ipa
    out_lang: eng-ipa
    rules_path: see-ipa_to_eng-ipa.json
  - authors:
      - Generated 2020-03-30 13:17:41.062858
    display_name: lml-ipa IPA to eng-ipa IPA
    in_lang: lml-ipa
    language_name: lml-ipa
    out_lang: eng-ipa
    rules_path: lml-ipa_to_eng-ipa.json
  - authors:
      - Generated 2020-04-27 01:30:32.371649
    case_sensitive: false
    display_name: oji-ipa IPA to eng-ipa IPA
    in_lang: oji-ipa
    language_name: oji-ipa
    norm_form: NFC
    out_lang: eng-ipa
    prevent_feeding: true
    rules_path: oji-ipa_to_eng-ipa.json
  - authors:
      - Generated 2020-07-28 14:28:24.895117
    case_sensitive: false
    display_name: gla-ipa IPA to eng-ipa IPA
    in_lang: gla-ipa
    language_name: gla-ipa
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    rules_path: gla-ipa_to_eng-ipa.json
  - authors:
      - Generated 2020-08-06 16:06:34.805350
    display_name: crk-ipa IPA to eng-ipa IPA
    in_lang: crk-ipa
    language_name: crk-ipa
    out_lang: eng-ipa
    rules_path: crk-ipa_to_eng-ipa.json
  - authors:
      - Generated 2021-03-07 22:23:34.538427
    case_sensitive: false
    display_name: tce-ipa IPA to eng-ipa IPA
    in_lang: tce-ipa
    language_name: tce-ipa
    out_lang: eng-ipa
    rules_path: tce-ipa_to_eng-ipa.json
  - authors:
      - Generated 2023-10-01 19:31:24.467200
    case_sensitive: false
    display_name: crg-ipa IPA to eng-ipa IPA
    in_lang: crg-ipa
    language_name: crg-ipa
    out_lang: eng-ipa
    prevent_feeding: true
    rules_path: crg-ipa_to_eng-ipa.json
  - authors:
      - Generated 2020-09-18 10:40:15.289530
      - Updated by hand 2021-02-10 Eric Joanis to handle ejectives
      - Update by hand 2021-05-21 Shankhalika Srikanth reorder rules with aspiration
    case_sensitive: false
    display_name: Tlingit IPA to English IPA
    in_lang: tli-ipa
    language_name: Tlingit IPA
    out_lang: eng-ipa
    prevent_feeding: true
    rules_path: tli-ipa_to_eng-ipa.json
  - authors:
      - Generated 2020-11-30 22:36:15.639360
    case_sensitive: false
    display_name: Gwich'in IPA to English IPA
    in_lang: gwi-ipa
    language_name: Gwich'in IPA
    out_lang: eng-ipa
    rules_path: gwi-ipa_to_eng-ipa.json
  - authors:
      - Generated 2022-09-09 13:04:46.128081
    case_sensitive: false
    display_name: mic-ipa IPA to eng-ipa IPA
    in_lang: mic-ipa
    language_name: mic-ipa
    out_lang: eng-ipa
    prevent_feeding: true
    rules_path: mic-ipa_to_eng-ipa.json
  - authors:
      - Generated 2021-03-08 17:26:16.371203
    display_name: iku-ipa IPA to eng-ipa IPA
    in_lang: iku-ipa
    language_name: iku-ipa
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    rules_path: iku-ipa_to_eng-ipa.json
  - authors:
      - Generated 2021-03-18 14:51:53.222666
    case_sensitive: false
    display_name: ikt-ipa IPA to eng-ipa IPA
    in_lang: ikt-ipa
    language_name: ikt-ipa
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    rules_path: ikt-ipa_to_eng-ipa.json
  - authors:
      - Generated 2021-03-18 16:13:29.007425
    case_sensitive: false
    display_name: iku-sro-ipa IPA to eng-ipa IPA
    in_lang: iku-sro-ipa
    language_name: iku-sro-ipa
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    rules_path: iku-sro-ipa_to_eng-ipa.json
  - authors:
      - Generated 2021-03-23 11:55:07.200851
    case_sensitive: false
    display_name: haa-ipa IPA to eng-ipa IPA
    in_lang: haa-ipa
    language_name: haa-ipa
    out_lang: eng-ipa
    rules_path: haa-ipa_to_eng-ipa.json
  - authors:
      - Generated 2021-03-07 23:35:39.198455
    case_sensitive: false
    display_name: ttm-ipa IPA to eng-ipa IPA
    in_lang: ttm-ipa
    language_name: ttm-ipa
    out_lang: eng-ipa
    rules_path: ttm-ipa_to_eng-ipa.json
  - authors:
      - Generated 2021-08-01 19:37:38.316339
    case_sensitive: false
    display_name: tau-ipa IPA to eng-ipa IPA
    in_lang: tau-ipa
    language_name: tau-ipa
    out_lang: eng-ipa
    rules_path: tau-ipa_to_eng-ipa.json
  - authors:
      - Generated 2023-08-15 12:26:00.528774
    case_sensitive: false
    display_name: moh-ipa IPA to eng-ipa IPA
    in_lang: moh-ipa
    language_name: moh-ipa
    norm_form: NFC
    out_lang: eng-ipa
    rules_path: moh-ipa_to_eng-ipa.json
  - authors:
      - Generated 2022-04-12 11:42:52.894700
    case_sensitive: false
    display_name: moh-ipa IPA to eng-ipa IPA
    in_lang: moh-ipa
    language_name: moh-ipa
    norm_form: NFC
    out_lang: hamming-eng-ipa
    rules_path: moh-ipa_to_hamming-eng-ipa.json
  - authors:
      - Generated 2022-04-11 16:24:52.967497
    display_name: moh-equiv dummy to dummy dummy
    in_lang: moh-equiv
    language_name: moh-equiv
    out_lang: dummy
    rule_ordering: apply-longest-first
    rules_path: moh-equiv_to_dummy.json
  - authors:
      - Generated 2022-04-11 16:24:52.967497
    display_name: moh-equiv dummy to hamming dummy
    in_lang: moh-equiv
    language_name: moh-equiv
    out_lang: hamming-dummy
    rule_ordering: apply-longest-first
    rules_path: moh-equiv_to_hamming-dummy.json
  - authors:
      - Generated 2022-04-12 10:47:28.528081
    display_name: str-equiv dummy to dummy dummy
    in_lang: str-equiv
    language_name: str-equiv
    out_lang: dummy
    rule_ordering: apply-longest-first
    rules_path: str-equiv_to_dummy.json
  - authors:
      - Generated 2022-04-12 10:47:28.528081
    display_name: str-equiv dummy to hamming dummy
    in_lang: str-equiv
    language_name: str-equiv
    out_lang: hamming-dummy
    rule_ordering: apply-longest-first
    rules_path: str-equiv_to_hamming-dummy.json
  - authors:
      - Generated 2022-04-12 10:57:49.409626
    display_name: und-ascii dummy to dummy dummy
    in_lang: und-ascii
    language_name: und-ascii
    out_lang: dummy
    rules_path: und-ascii_to_dummy.json
  - authors:
      - Generated 2022-04-12 10:56:44.604694
    display_name: und-ascii dummy to dummy dummy
    in_lang: und-ascii
    language_name: und-ascii
    out_lang: hamming-dummy
    rules_path: und-ascii_to_hamming-dummy.json
  - authors:
      - Generated 2022-05-20 16:36:31.566493
    display_name: iku-ipa to hamming-eng-ipa
    in_lang: iku-ipa
    language_name: IPA
    norm_form: NFC
    out_lang: hamming-eng-ipa
    prevent_feeding: true
    rule_ordering: apply-longest-first
    rules_path: iku-ipa_to_hamming-eng-ipa.json
  - authors:
      - Generated 2022-05-20 16:55:13.188319
    display_name: und-ipa to hamming-eng-ipa
    in_lang: und-ipa
    language_name: IPA
    norm_form: NFC
    out_lang: hamming-eng-ipa
    prevent_feeding: true
    rule_ordering: apply-longest-first
    rules_path: und-ipa_to_hamming-eng-ipa.json
  - authors:
      - Generated 2022-05-20 19:12:51.416268
    display_name: ikt-ipa to hamming-eng-ipa
    in_lang: ikt-ipa
    language_name: IPA
    norm_form: NFC
    out_lang: hamming-eng-ipa
    prevent_feeding: true
    rule_ordering: apply-longest-first
    rules_path: ikt-ipa_to_hamming-eng-ipa.json
  - authors:
      - Generated 2022-06-07 10:24:54.512807
    display_name: moe-ipa to eng-ipa
    in_lang: moe-ipa
    language_name: IPA
    norm_form: NFC
    out_lang: eng-ipa
    prevent_feeding: true
    rule_ordering: apply-longest-first
    rules_path: moe-ipa_to_eng-ipa.json
  - authors:
      - Generated 2022-07-22 13:54:50.454043
    case_sensitive: false
    display_name: win-ipa IPA to eng-ipa IPA
    in_lang: win-ipa
    language_name: win-ipa
    norm_form: NFC
    out_lang: eng-ipa
    prevent_feeding: true
    rule_ordering: apply-longest-first
    rules_path: win-ipa_to_eng-ipa.json
  - authors:
      - Generated 2022-07-20 06:53:42.624015
      - Updated by hand 2021-07-20 David Huggins-Daines to improve vowels
    case_sensitive: false
    display_name: fin-ipa IPA to eng-ipa IPA
    in_lang: fin-ipa
    language_name: fin-ipa
    norm_form: NFC
    out_lang: eng-ipa
    prevent_feeding: true
    rule_ordering: apply-longest-first
    rules_path: fin-ipa_to_eng-ipa.json
  - authors:
      - Generated 2023-01-13 11:12:51.451010
    display_name: oka-ipa to eng-ipa
    in_lang: oka-ipa
    language_name: IPA
    norm_form: NFC
    out_lang: eng-ipa
    prevent_feeding: true
    rule_ordering: apply-longest-first
    rules_path: oka-ipa_to_eng-ipa.json
  - authors:
      - Generated 2023-06-26 15:06:13.793560
    display_name: clm-ipa to eng-ipa
    in_lang: clm-ipa
    language_name: IPA
    norm_form: NFC
    out_lang: eng-ipa
    prevent_feeding: true
    rule_ordering: apply-longest-first
    rules_path: clm-ipa_to_eng-ipa.json
