<<: &shared
  language_name: Hoocąk
mappings:
  - display_name: Hoocąk to IPA
    mapping: win_to_ipa.json
    in_lang: win
    out_lang: win-ipa
    case_sensitive: false
    authors:
      - David Huggins Daines
    <<: *shared
  - display_name: Hoocąk IPA to English IPA
    mapping: win_ipa_to_eng_ipa.json
    in_lang: win-ipa
    out_lang: eng-ipa
    rule_ordering: apply-longest-first
    authors:
      - David Huggins Daines
    <<: *shared
