<<: &shared
  language_name: Northern East Cree
mappings:
  - display_name: Northern East Cree Equivalencies
    in_lang: crl
    out_lang: crl-equiv
    type: mapping
    authors:
      - Delasie Torkornoo
      - Aidan Pine
    mapping: crl_equiv.json
    <<: *shared
  - display_name: Northern East Cree to IPA
    in_lang: crl-equiv
    out_lang: crl-ipa
    type: mapping
    authors:
      - David Huggins-Daines
      - Patrick Littell
      - Delasie Torkornoo
    mapping: crl_to_ipa.json
    <<: *shared
  - display_name: Northern East Cree IPA to English IPA
    in_lang: crl-ipa
    out_lang: eng-ipa
    type: mapping
    mapping: crl_ipa_to_eng_ipa.json
    rule_ordering: apply-longest-first
    <<: *shared
