<<: &shared
  language_name: Michif
mappings:
  - display_name: Michif Turtle Mountain Dictionary (TMD) to Michif IPA
    mapping: crg-tmd-to-crg-ipa.csv
    in_lang: crg-tmd
    out_lang: crg-ipa
    case_sensitive: false
    rule_ordering: as-written
    prevent_feeding: true
    abbreviations: abbreviations.csv
    authors:
      - Fineen Davis
      - Olivia Sammons
      - Heather Souter
      - Christopher Cox
    <<: *shared
  - display_name: Michif Double Vowel (DV) to Michif IPA
    mapping: crg-dv-to-crg-ipa.csv
    in_lang: crg-dv
    out_lang: crg-ipa
    rule_ordering: as-written
    prevent_feeding: true
    case_sensitive: false
    authors:
      - Fineen Davis
      - Olivia Sammons
      - Heather Souter
      - Christopher Cox
    <<: *shared
