<<: &shared
  language_name: Southern Tutchone
mappings:
  - display_name: Southern Tutchone normalization
    in_lang: tce
    out_lang: tce-norm
    authors:
      - Shankhalika Srikanth
    type: mapping
    mapping: tce_norm.csv
    prevent_feeding: false
    rule_ordering: as-written
    case_sensitive: false
    norm_form: NFC
    <<: *shared
  - display_name: Southern Tutchone to IPA
    in_lang: tce-norm
    out_lang: tce-ipa
    authors:
      - Shankhalika Srikanth
    type: mapping
    mapping: tce_to_ipa.csv
    prevent_feeding: true
    rule_ordering: as-written
    case_sensitive: false
    norm_form: NFC
    <<: *shared
