<<: &shared
  language_name: Halkomelem
mappings:
  - display_name: Halkomelem APA to Hul’q’umi’num’ (Island) practical orthography
    in_lang: hur_apa
    out_lang: hur_orthog
    authors:
      - Zack Gilkison
    type: mapping
    rules_path: hur_apa_to_hur_orthog.json
    prevent_feeding: false
    rule_ordering: apply-longest-first
    case_sensitive: false
    norm_form: NFD
    # <<: &shared
  - display_name: Halkomelem APA to Hul’q’umi’num’ (Island) practical orthography
    in_lang: hur_orthog
    out_lang: hur_apa
    authors:
      - Zack Gilkison
    type: mapping
    rules_path: hur_orthog_to_hur_apa.json
    prevent_feeding: true
    rule_ordering: apply-longest-first
    case_sensitive: false
    norm_form: NFD
    language_name: Halkomelem
