<<: &shared
  language_name: nsyilxcən
mappings:
  - display_name: nsyilxcən to IPA
    mapping: nsy_to_ipa.csv
    in_lang: nsy
    out_lang: nsy-ipa
    authors:
      - Craig Carpenter
    type: mapping
    prevent_feeding: true
    rule_ordering: apply-longest-first
    norm_form: NFC
    <<: *shared
