name: Deploy docs
on:
  push:
    branches:
      - main
jobs:
  docs:
    # Create latest docs
    runs-on: ubuntu-latest
    permissions:
      contents: write  # to deploy to gh-pages
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # fetch all commits/branches
          persist-credentials: true  # so we can deploy to gh-pages
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]
      - name: Setup doc deploy
        run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Deploy docs with mike ðŸš€
        run: |
          mike deploy --push --update-aliases dev latest
